# Default target.
.DEFAULT_GOAL := all
.PHONY: all
all: begin gccversion sizebefore build sizeafter end



# Eye candy.
# AVR Studio 3.x does not check make's exit code but relies on
# the following magic strings to be generated by the compile job.
.PHONY: begin
begin:
	@echo
	@echo $(MSG_BEGIN)

.PHONY: end
end:
	@echo $(MSG_END)
	@echo

